apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: second-app-bar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/devher0/argo-cd-test.git
    targetRevision: HEAD
    path: environments/staging/second-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true